### PR TITLE
Fix trailing comma in destructuring rest spread

### LINKED ISSUE #559: Trailing comma in destructuring rest spread property breaks code
When `print` option `trailingComma` used, and one of nodes in object destructuring removed, trailing comma added to spread operator which leads to broken code:

```js
const { ...b,} = obj
           ^

SyntaxError: Rest element must be last element
```

Code to reproduce:

```js
const babel = require('@babel/parser');
const traverse = require('@babel/traverse').default;
const generate = require('@babel/generator').default;
const recast = require('recast');

const source = `
    const {
        a,
        ...b
    } = obj;
`;

const babelAST = recast.parse(source, {
    parser: {
        parse: babel.parse,
    }
});

let once = false;
traverse(babelAST, {
    enter(path) {
        if (once)
            return;

        if (path.type !== 'ObjectProperty')
            return;

        path.remove();
        once = true;
    }
});

console.log(recast.print(babelAST, {
    trailingComma: true,
}));
// outputs
// PrintResult { code: '\n    const {\n        ...b,\n    } = obj;\n' }
```
Will be great to not add comma when rest spread used :)

### PR DESCRIPTION
**Pull request by Daniel15**
When the `trailingComma` option is enabled, we shouldn't append a trailing comma to a rest spread.

Closes #559

### CODE REVIEW

File: lib/printer.ts [hunk 1]
```diff
@@ -717,7 +718,11 @@ function genericPrintNoParens(path: any, options: any, print: any) {
                     allowBreak = !multiLine;
                 } else if (len !== 1 && isTypeAnnotation) {
                     parts.push(separator);
-                } else if (!oneLine && util.isTrailingCommaEnabled(options, "objects")) {
+                } else if (
+                    !oneLine && 
+                    util.isTrailingCommaEnabled(options, "objects") &&
+                    childType !== 'RestElement'
```
Comment (eventualbuddha) [inline lib/printer.ts:724]: Inline `childType`? Unless I’m missing why it should be hoisted.

Comment (Daniel15) [reply lib/printer.ts]: Will do!

**Comment by Daniel15** [comment]
Thanks for merging!
