### PR TITLE
Printing support for property initializers.

### LINKED ISSUE #188: Support for ES7 Property Initializers
Was trying to use `recast` on a react project and ran into an issue with it not being able to parse `static` property initializers. For example:

```
class App extends Component {
  static defaultProps = { /* ... */ };
}
```

Which results in an unexpected token error. Since these are ES7+ I understand why I shouldn't expect this to work, but is there any way for `recast` to parse these initializers and, if not, is there any way that I can add them to `ast-types` to allow me to visit these properties when going through the AST? Thanks!

### PR DESCRIPTION
**Pull request by cpojer**
This adds printing support for property initializers in "ES7".

Depends on https://github.com/benjamn/ast-types/pull/117 and https://github.com/benjamn/recast/pull/179 – I can remove the other recast diff though, just accidentally stacked it on top.
Fixes #188

### CODE REVIEW

File: lib/printer.js [hunk 1]
```diff
@@ -1101,11 +1105,19 @@ function genericPrintNoParens(path, options, print) {
...
 
     case "ClassProperty":
-        return concat([
-            path.call(print, "key"),
-            path.call(print, "typeAnnotation"),
-            ";"
-        ]);
+        var parts = [];
+        if (n.static)
+            parts.push("static ");
```
Comment (benjamn) [inline lib/printer.js]: I've started listening to my orthodontist and putting braces on everything, though you can be forgiven for following the existing style in this file :)

File: lib/printer.js [hunk 2]
```diff
@@ -279,7 +279,11 @@ function genericPrintNoParens(path, options, print) {
         if (n.async)
             parts.push("async ");
 
-        if (n.params.length === 1 && !n.rest) {
+        if (
+            n.params.length === 1 &&
+            !n.rest &&
+            n.params[0].type !== 'SpreadElementPattern'
```
Comment (benjamn) [inline lib/printer.js]: This commit looks reasonable to me, too!

File: lib/printer.js (hunk 1 above)
Comment (cpojer) [inline lib/printer.js]: nice! I'd reserve adding braces for a separate pull request though, just following your conventions. How do you feel about spaces instead of tabs? :P

Comment (benjamn) [inline lib/printer.js]: NO TABS EVER

**Comment by cpojer** [comment]
Seems like the tests are failing because ast-types is not updated. I guess I'll have to wait for you to merge the change to ast-types, publish it and then go back to this diff and update package.json?

**Comment by benjamn** [comment]
Want to rebase and see if the tests pass now?

**Comment by cpojer** [comment]
works!

**Comment by cpojer** [comment]
wohoo!
