### PR TITLE
Fix parens for object destructuring assignment expression

### LINKED ISSUE #412: Invalid code generated for object destructuring assignment
This valid code:

```js
({ x } = { x : 1 })
```

Is printed by `recast.prettyPrint` as:

```js
{ x } = { x : 1 }
```

Which breaks the syntax. The parentheses are mandatory.

```js
> eval('({x}={x:1})')
{ x: 1 }
> x
1
> eval('{x}={x:1}')
SyntaxError: Unexpected token =
```

### PR DESCRIPTION
**Pull request by ef4**
Fixes #412.

### CODE REVIEW

File: lib/fast-path.js [hunk 1]
```diff
@@ -183,13 +183,21 @@ FPp.map = function map(callback/*, name1, name2, ... */) {
...
+  if (node.type === "AssignmentExpression" && node.left.type === 'ObjectPattern') {
+    return true;
+  }
+
   var parent = this.getParentNode();
   if (!parent) {
     return false;
   }
 
-  var name = this.getName();
```
Comment (benjamn) [inline lib/fast-path.js]: Might want to keep the `name` line down here, since root/parentless nodes don't have names?

**Comment by ef4** [comment]
@benjamn I incorporated your feedback

**Comment by benjamn** [comment]
Great, thanks so much @ef4!
