### PR TITLE
Fix issue with export default template literals

### LINKED ISSUE #414: Bug - Can't Export Default Template String
First off, this library is awesome, so thank you! 😄 Using it with `jscodeshift`.

#### Description
[`export default`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) allows any expression to be exported, but exporting a template string causes a TypeError in `recast`.
#### Code Snippet
```
const ast2 = recast.parse("export default `hello world`;");
// Error: Uncaught TypeError: Cannot read property 'start' of null at fixTemplateLiteral
```
#### Reproduce
https://esnextb.in/?gist=f49ee2da9306734bb4813ebcff734c38
#### Fix
Looks like the line of code where the TypeError gets thrown is accessing `node.loc.start` in [`fixTemplateLiteral`](https://github.com/benjamn/recast/blob/98599d1a36a686919b5fcf47616884bad9ac790a/lib/util.js#L262).

### PR DESCRIPTION
**Pull request by ganemone**
This fixes an issue where exporting a template literal as default caused the parser to fail. It also adds a regression test.

Fixes #414

### CODE REVIEW

File: lib/util.js [hunk 1]
```diff
@@ -265,25 +265,28 @@ function fixTemplateLiteral(node, lines) {
     // If there are no quasi elements, then there is nothing to fix.
     return;
   }
+  
+  // node.loc is not present when using export default with a template literal
```
Comment (benjamn) [inline lib/util.js]: Any idea why `node.loc` would be missing?

Comment (ganemone) [reply lib/util.js]: Not sure to be honest. I can reproduce this with the regression test however. I also can reproduce this with `@babel/parser`, even with `ranges` turned on.

**Comment by ganemone** [comment]
Any reservations on merging this?

File: lib/util.js (hunk 1 above)
Comment (benjamn) [reply lib/util.js]: Ahh, that's something we do in a few places to disable reprinting problematic nodes, e.g. [here](https://github.com/benjamn/recast/blob/45773b02ad1dfbd61ac0050df17587d0d83dca7e/lib/util.js#L186-L188).

This PR is definitely safe/fine for now. Sorry for the wait!
